dispatchrun/dispatch-py

tests/dispatch/test_scheduler.py

Fix for this error, not sure why it didn't occur in CI, I may have a different version of protobuf.
```
================================================ FAILURES ================================================
______________________ TestOneShotScheduler.test_resume_after_gather_one_at_a_time _______________________
self = <tests.dispatch.test_scheduler.TestOneShotScheduler testMethod=test_resume_after_gather_one_at_a_time>
def test_resume_after_gather_one_at_a_time(self):
@durable
async def main():
return sum(await call_concurrently("a", "b", "c", "d"))
output = self.start(main)
calls = self.assert_poll_call_functions(output, ["a", "b", "c", "d"])
for i, call in enumerate(calls):
output = self.resume(
main,
output,
[CallResult.from_value(i, correlation_id=call.correlation_id)],
)
if i < …
```

fix scheduler test

---

pyproject.toml
src/dispatch/proto.py
src/dispatch/scheduler.py
src/dispatch/status.py
tests/dispatch/test_error.py
tests/dispatch/test_status.py

This PR fixes error propagation through the call stack of durable coroutines.
I have added a dependency on the [tblib](https://pypi.org/project/tblib/) package to deal with parsing stack traces and reconstructing traceback objects which is quite tricky to do since these values can only be constructed by the interpreter when raising exceptions ([see](https://python-tblib.readthedocs.io/en/latest/_modules/tblib.html#Traceback.as_traceback)).
Using this code example:
```python
from fastapi import FastAPI
from dispatch.fastapi import Dispatch
app = FastAPI()
dispatch = Dispatch(app)
@dispatch.coroutine()
async def get(something):
raise ValueError("This is an error")
@dispatch.coroutine()
async def publish():
return await get.call("this")
@app.get("/")
def root():
publish.dispatch()
return …
```

propagate exception traceback

---

src/dispatch/client.py
src/dispatch/coroutine.py
src/dispatch/experimental/durable/function.py
src/dispatch/experimental/durable/registry.py
src/dispatch/fastapi.py
src/dispatch/function.py
src/dispatch/proto.py
src/dispatch/scheduler.py
src/dispatch/signature/key.py
src/dispatch/signature/request.py

This will help ensure we are correctly accessing fields that are explicitly declared. It also has memory footprint implications since the interpreter avoids creating a dictionary to maintain the state of the objects.
Where available, I configured the `@dataclass` decorator to automatically generate the `__slots__` attribute. In the few other places where we weren't using `@dataclass`, I declared the slots explicitly.

add slots declarations

---

tests/test_client.py

The original error printed by mypy:
```
tests/test_client.py:29: SyntaxWarning: invalid escape sequence '\('
"Dispatch received an invalid authentication token \(check DISPATCH_API_KEY is correct\)",
tests/test_client.py:40: SyntaxWarning: invalid escape sequence '\('
"Dispatch received an invalid authentication token \(check api_key is correct\)",
```
Luckily in python all unrecognized escape sequences are left in the string unchanged, so it still worked.

Fix invalid escape sequence in client test regexps

---

src/dispatch/fastapi.py
src/dispatch/signature/digest.py
tests/dispatch/signature/test_signature.py
tests/test_full.py

This PR changes the FastAPI adapter to return error responses in the format expected by the Connect protocol (see https://connectrpc.com/docs/protocol/#error-end-stream).
All errors will now be reported as a http response with a non-200 status code, and a JSON body with this shape:
```json
{
"code": "...",
"message": "..."
}
```
Two status codes are now reserved to indicate issues with http request signatures:
- **401** for the `ValueError` raised when the signature uses an unsupported hashing algorithm or when it didn't contain all the expected attributes (these should never occur when connected to the Dispatch platform)
- **403** for any other verification failures related to the signing keys

FastAPI: return error responses formatted for the connectrpc protocol

---

README.md
examples/auto_retry/app.py
examples/getting_started/app.py
src/dispatch/experimental/durable/function.py
src/dispatch/function.py
src/dispatch/scheduler.py
tests/test_full.py

This PR removes the exported `dispatch.coroutine` decorator and integrates the functionality under `dispatch.function`. The intent is to minimize the API footprint and limit the chances of misusing it (e.g., it's impossible to mistakenly pass a Python coroutine to `dispatch.function` and vice versa).
As I was working through this PR, I made two related changes:
- **dispatch.function can now be used without arguments:** this is a common pattern in Python, we were requiring the decorator to be used as a function call (e.g., a call returning a decorator) to future-proof the need to pass arguments to the decorator. I changed the construct so that both syntaxes are supported, so we remain future-proof but can also simplify the declaration when there is no need for arguments.
- **coroutines …

Remove coroutine decorator

---

src/dispatch/function.py

Fixes a regression introduced in #79 
The problem was caused by wrapping the original function with the `durable` decorator, which loses information about the fact that the underlying function is a coroutine. Using `inspect.iscoroutinefunction` on the decorated object always returns `False`.
The fix isn't the most pretty, basically adding a boolean parameter (what can't be fixed by an extra boolean? 😅) to track whether we are registering a coroutine or a simple function.

fix coroutine decoration

---

src/dispatch/proto.py
tests/dispatch/test_error.py

Fix for this error:
```
tblib.TracebackParseError: Could not find any frames in ''.
```

don't crash on missing error traceback

---

src/dispatch/fastapi.py
src/dispatch/proto.py
src/dispatch/scheduler.py
src/dispatch/sdk/v1/poll_pb2.py
src/dispatch/sdk/v1/poll_pb2.pyi
tests/dispatch/test_scheduler.py

This fixes https://github.com/stealthrocket/dispatch-sdk-python/issues/87.
When there's an error polling, we now raise an error in the coroutines that are waiting on a call that was made before the previous yield. Other in-flight calls are not affected.

Handle PollResult errors

---

src/dispatch/proto.py
src/dispatch/scheduler.py
src/dispatch/sdk/v1/poll_pb2.py
src/dispatch/sdk/v1/poll_pb2.pyi
src/dispatch/test/server.py
src/dispatch/test/service.py
tests/dispatch/test_scheduler.py

The local coroutine scheduler (#52) now uses the `min_results` setting from https://github.com/stealthrocket/dispatch-sdk-protobuf/pull/14 to improve polling latency & throughput.
Most users should find the default polling configuration satisfactory. Power users can instantiate their own scheduler and play around with the settings to tune latency & throughput. I've documented the available settings for these users.

Use min_results when polling

---

src/dispatch/scheduler.py
tests/dispatch/test_scheduler.py

This addresses an issue that might occur when overriding  `poll_min_results` from https://github.com/stealthrocket/dispatch-sdk-python/pull/92. If the value is less than the number of outstanding calls, Dispatch will unconditionally wait until the deadline (`poll_max_wait_seconds`). If no deadline is provided, Dispatch will never resume the coroutine and it will eventually expire.
This is not an issue with the default (`poll_min_results=1`) since there will always be at least one outstanding call when the scheduler yields to Dispatch (at least, until we introduce support for timers/sleep).
This PR fixes the issue by clamping `min_results` if it's greater than the number of outstanding calls.

Clamp min_results if greater than outstanding calls

---

src/dispatch/function.py
tests/dispatch/test_function.py
tests/test_fastapi.py

This PR improves type safety by using `ParamSpec` for the registration decorators.
mypy now rejects invalid arguments to `__call__` or to `.dispatch` on the decorated function:
```python
@dispatch.function
async def foo(a: int, b: str = "foo") -> list[str]:
return [b] * a
foo(1, "abc")              # ok
foo.dispatch(2, b="xyz")   # ok
foo("oops")                # error: Expected type 'int', got 'str' instead
```
I added `py.typed` files to our packages to indicate that type information is available. See https://peps.python.org/pep-0561/ for more information.
I had to make one breaking change, which is that the `@dispatch.function` and `@dispatch.primitive_function` decorators no longer accept parameters and return a decorator. These must be used as decorators directly, e.g. …

Improve type safety with ParamSpec

---

src/dispatch/function.py

This PR improves type checking of calls to functions registered via `@dispatch.function`. The previous PR improved type checking of call arguments (https://github.com/stealthrocket/dispatch-py/pull/100), while this PR focuses on call results.
The wrapped functions now return a `Coroutine[Any, Any, T]` when called, allowing mypy to check that the resulting coroutines are awaited properly, and that the return values (of type `T`) are used correctly. Here's an example of both new errors:
```python
@dispatch.function
async def foo(a: int, b: str = "foo") -> list[str]:
return [b] * a
@dispatch.function
async def bar() -> str:
results = await foo(1, "x")
return results[0] + 3            # error: Unsupported operand types for + ("str" and "int")
foo(1, "abc")                        # error: …
```

Improve type checking of call results

---

examples/fanout/fanout.py

- remove timecraft from the examples since we archived the repository
- rename dispatch-sdk-python to dispatch-py

fix repositories in fanount example

---

src/dispatch/fastapi.py

We were depending on `httpx` only for the `_urlparse` function. I believe `urllib` is less strict and could let through URLs that miss required fields, we can address these later.
Note that we still have a dev dependency on `httpx`, this PR only removes the dependency from the core SDK.
Fixes #112

remove httpx dependency from dispatch.fastapi module

---

src/dispatch/experimental/durable/function.py

[mypy 1.9](https://github.com/python/mypy/releases/tag/1.9.0) was released recently. There's a new warning, which is fixed by this PR.

Fix a mypy 1.9 error

---

src/dispatch/fastapi.py
tests/test_fastapi.py

Verification keys can now be provided in either PEM format, or as a base64-encoded string.
This fixes #115.

Improve UX around verification keys

---

README.md
src/dispatch/experimental/durable/function.py

This PR adds a section to the README discussing how coroutines are serialized, and what issues might be encountered. 
The `DURABLE_TRACE=1` environment variable is described here (fixing https://github.com/stealthrocket/dispatch-py/issues/116).

Add section describing serialization and its quirks

---

README.md
pyproject.toml
src/dispatch/scheduler.py
src/dispatch/status.py
src/dispatch/test/__main__.py
src/dispatch/test/server.py
src/dispatch/test/service.py
tests/test_client.py

It's difficult to try out Dispatch today. Users either have to use ngrok to expose their test functions to the production Dispatch instance, or must manually fit the pieces together from the `dispatch.test` package (#86) to setup a local server that they can connect to.
This PR introduces a front-end to the components in the `dispatch.test` package, via a `python -m dispatch.test` command. Users can use this to quickly spin up a mock Dispatch server locally.
```
$ python -m dispatch.test --help
Mock Dispatch server for use in test environments.
Usage:
dispatch.test <endpoint> [--api-key=<key>] [--hostname=<name>] [--port=<port>] [-v | --verbose]
dispatch.test -h | --help
Options:
--api-key=<key>      API key to require when clients connect to the server [default: test].
--hostname=<name> …
```

Mock server

---

src/dispatch/function.py
tests/test_full.py

This fixes a bug where synchronous functions are registered with an incorrect function name (`{func.__qualname__}_async`).

Fix registration of synchronous functions

---

src/dispatch/test/service.py

This PR improves logging when a call from the mock server fails (https://github.com/stealthrocket/dispatch-py/pull/126).
Before:
```
2024-03-18 13:53:45 [WARN] call to function send_message failed (PERMANENT_ERROR)
```
After:
```
2024-03-18 13:53:45 [WARN] call to function send_message failed (PERMANENT_ERROR => NameError: name 'resopnse' is not defined)
```

mock server: show more info when a call fails

---

pyproject.toml

`docopt` — used by the mock server (#126) — is part of the dev dependencies. This PR promotes the dependency so that the mock server is available with normal installs of the package.

Promote docopt dependency

---

src/dispatch/integrations/__init__.py
src/dispatch/integrations/slack.py

This PR adds an integration for the [Slack SDK](https://github.com/slackapi/python-slack-sdk). If exceptions such as `slack_sdk.errors.SlackApiError` are raised, the error will be categorized correctly so that temporary errors are automatically retried.

Slack integration

---

src/dispatch/integrations/__init__.py
src/dispatch/integrations/openai.py

This PR adds an integration for the [OpenAI SDK](https://github.com/openai/openai-python). If exceptions such as `openai.APIStatusError` are raised, the error will be categorized correctly so that temporary errors are automatically retried.

OpenAI integration

---

src/dispatch/__init__.py
src/dispatch/coroutine.py
src/dispatch/scheduler.py
tests/dispatch/test_scheduler.py

The SDK provides a `gather` function to concurrently run coroutines and collect their results. It returns as soon as _all_ results are available, and raises if _any_ coroutine raises.
This PR introduces `all`, `any` and `race` which cover more concurrency use cases. See https://github.com/stealthrocket/dispatch-py/issues/88 for more information.
This fixes https://github.com/stealthrocket/dispatch-py/issues/88.

Concurrency primitives: any, all, race

---

src/dispatch/__init__.py
src/dispatch/fastapi.py
src/dispatch/function.py
tests/dispatch/test_function.py

This PR reworks the `Registry` class so that it can be used to register and dispatch calls to functions hosted on remote endpoints.
```python
from dispatch import Registry
remote = Registry("http://some.foreign.endpoint/")
@remote.function
def foo(bar: int) -> str: ...
```
You only need to register a stub for remote functions. You can then dispatch calls to them (e.g. `foo.dispatch(bar)`), and also use them within a local function/coroutine (e.g. `await foo(bar)`). Type checking works as expected in both cases.

Remote endpoints

---

pyproject.toml

Same issue as https://github.com/stealthrocket/dispatch-py/pull/130. The `dispatch.test` package relies on `httpx` to make requests to the endpoint. The package and `python -m dispatch.test` command don't work if `httpx` is only a dev dependency.

Promote httpx dependency

---

src/dispatch/fastapi.py
src/dispatch/function.py
src/dispatch/test/__main__.py

Two improvements I noticed:
* I moved the `batch` helper from `dispatch.fastapi.Dispatch` to the `dispatch.function.Registry` base class, so that it can be used when you construct a remote endpoint registry (#134)
* when quitting the `python -m dispatch.test` server with SIGINT / Ctrl+C, previously it would print a stack trace from where the `KeyboardInterrupt` was raised. Now it prints a nice single-line exit message

Minor UX improvements

---

.github/workflows/test.yml
pyproject.toml
src/dispatch/experimental/durable/frame.c
src/dispatch/experimental/durable/frame.pyi
src/dispatch/experimental/durable/frame310.h
src/dispatch/experimental/durable/frame311.h
src/dispatch/experimental/durable/frame312.h
src/dispatch/experimental/durable/frame313.h
src/dispatch/experimental/durable/function.py
tests/dispatch/experimental/durable/test_coroutine.py
tests/dispatch/experimental/durable/test_generator.py

This PR adds support for Python 3.10.
Versions prior to 3.11 have an additional stack of "blocks" on each frame that need to be persisted. We now store this information along with a "block pointer" so that we can later restore the frame properly. 
In https://github.com/stealthrocket/dispatch-py/pull/136/commits/703f1e8c21c5bf86d569ee15af137d4297a6d2e2, I changed the extension so that it's more verbose when it comes to handling the differences across Python versions. Previously we were using macros with range checks, and aliasing fields that had the same structure but used different names across versions. Given the divergence in frame structures across Python 3.10 and 3.11, I felt it was better to be explicit and verbose when dealing with differences across versions. There'll now be a …

Python 3.10 support

---

.github/workflows/test.yml
pyproject.toml
src/dispatch/coroutine.py
src/dispatch/experimental/durable/frame.c
src/dispatch/experimental/durable/frame.pyi
src/dispatch/experimental/durable/frame309.h
src/dispatch/experimental/durable/function.py
src/dispatch/experimental/durable/registry.py
src/dispatch/fastapi.py
src/dispatch/function.py
src/dispatch/id.py
src/dispatch/integrations/http.py
src/dispatch/integrations/httpx.py
src/dispatch/integrations/openai.py
src/dispatch/integrations/requests.py
src/dispatch/integrations/slack.py
src/dispatch/proto.py
src/dispatch/scheduler.py
src/dispatch/signature/digest.py
src/dispatch/signature/key.py
src/dispatch/signature/request.py
src/dispatch/status.py
src/dispatch/test/client.py
src/dispatch/test/service.py
tests/dispatch/experimental/durable/test_frame.py
tests/dispatch/test_error.py
tests/dispatch/test_scheduler.py

This PR adds support for Python 3.9.
I had to refactor to avoid things only available in 3.10+:
* `match` ([PEP 636](https://peps.python.org/pep-0636/))
* union types ([PEP 604](https://peps.python.org/pep-0604/))
* `@dataclass(slots=True)`
* `traceback.format_exception` with a single argument
I could add `__slots__` manually, but I think this is in premature optimization territory.
This fixes #43.

Python 3.9 support

---

.github/workflows/test.yml
pyproject.toml
src/dispatch/coroutine.py
src/dispatch/experimental/durable/frame.c
src/dispatch/experimental/durable/frame308.h
src/dispatch/experimental/durable/function.py
src/dispatch/experimental/durable/registry.py
src/dispatch/function.py
src/dispatch/proto.py
src/dispatch/scheduler.py
src/dispatch/signature/__init__.py
src/dispatch/status.py
src/dispatch/test/server.py
src/dispatch/test/service.py
tests/dispatch/test_scheduler.py

Following on from #136 and #140, this PR adds support for Python 3.8. This is the last version of Python that's officially supported (https://devguide.python.org/versions/#supported-versions). Python 3.7 was EOL'd in June 2023.
The only major change is that we need to use `typing.{List,Tuple,Set,Dict,Type}` instead of `{list,tuple,set,dict,type}` as [PEP 585](https://peps.python.org/pep-0585/) isn't available until 3.9.
The frame and generator objects are identical to 3.9.

Python 3.8 support

---

.github/workflows/test.yml
Makefile
tests/examples

Running `make test` checks types with `mypy`, then runs tests found in the `./tests` directory. At the moment we symlink `./examples` as `./test/examples` so that we test the examples when running `make test`.
Given that our build matrix is growing (#136, #140, #143), we may run into a situation where the examples hit rate limits when run for each Python version, causing CI to fail. For this reason, I've removed the symlink so that we don't test examples by default.
I've added a new make command that tests the examples. We can run this locally as necessary. To ensure we at least have some coverage, I've added a single CI run that will test the examples using Python 3.12 only.

Don't test ./examples by default

---

src/dispatch/__init__.py
src/dispatch/function.py
src/dispatch/proto.py
src/dispatch/scheduler.py
tests/dispatch/test_scheduler.py

This PR adds a new `Reset` type which is intended to be used to allow resetting the current coroutine execution to a different pair of function and arguments.
In the inner layers of the SDK, this construct gets turned into a tail call with a temporary error status to communicate the failure to the scheduler (and apply back-pressure) while also changing the input arguments.

add special Reset class to implement tail calls

---

src/dispatch/fastapi.py

The FastAPI integration now runs Dispatch functions in a thread executor to avoid blocking the underlying asyncio event loop used by FastAPI and Starlette.

FastAPI: run Dispatch functions in a thread executor

---

.github/workflows/test.yml
Makefile
examples/auto_retry/test_app.py
examples/getting_started/test_app.py
examples/github_stats/test_app.py
pyproject.toml
src/dispatch/experimental/lambda_handler.py
src/dispatch/fastapi.py
src/dispatch/function.py
src/dispatch/proto.py
src/dispatch/scheduler.py
src/dispatch/sdk/v1/call_pb2.py
src/dispatch/sdk/v1/dispatch_pb2.py
tests/dispatch/test_error.py
tests/dispatch/test_status.py
tests/test_fastapi.py

This change is an experimental Lambda integration. It mostly works but comes with a few caveats.
Instead of going with a new decorator to register the entrypoint for the Lambda, we can pass an optional function name to the handler:
```
def handler(event, context):
dispatch.handle(event, context, entrypoint="myentrypoint")
```
If no entrypoint is defined, we expect the function to be defined in the RunRequest.

Add experimentation Lambda integration

---

src/dispatch/proto.py
src/dispatch/scheduler.py
tests/test_fastapi.py

Coroutine state is currently pickled twice, [here](https://github.com/stealthrocket/dispatch-py/blob/c9cdf68b891e5bf09ab008870d01f95842033c87/src/dispatch/scheduler.py#L544) and [here](https://github.com/stealthrocket/dispatch-py/blob/main/src/dispatch/proto.py#L232). This PR fixes the issue by requiring that coroutine state is bytes when it reaches the latter. This allows the bundled scheduler to be responsible for serializing the state, where it can check that the state is valid and raise an `IncompatibleStateError` otherwise.

Don't pickle coroutine state twice

---

.github/workflows/pypi.yml

https://github.com/pypa/cibuildwheel/releases/tag/v2.17.0 includes a fix (https://github.com/pypa/cibuildwheel/pull/1745) for the issue we're seeing building wheels and publishing to PyPI: https://github.com/stealthrocket/dispatch-py/actions/runs/8532064505

Bump cibuildwheel version to fix PyPI publish issue

---

src/dispatch/fastapi.py

There's no need to verify requests that come through the CLI.

Don't print verification key warning when running under Dispatch CLI

---

examples/github_stats/app.py
src/dispatch/error.py
src/dispatch/status.py
tests/dispatch/test_status.py

Dispatch does a good job of categorizing errors automatically. In some cases though it doesn't have enough information to be able to choose the correct function call status.
For example, in the GitHub example, the function has to manually check for a 403 response when a rate limit has been exceeded, and has no way of signalling to the Dispatch handler that it's a throttling error rather than a `403 Forbidden` error.
This PR adds new error types that users can use in these cases.

Add dedicated error types for each of the error statuses

---

README.md
docs/index.md
examples/fanout/fanout.py
examples/github_stats/app.py

This will address these failures in tests due to redirects not being handled by the http client https://github.com/dispatchrun/dispatch-py/actions/runs/8915493071/job/24485224353?pr=159

update URLs from stealthrocket to dispatchrun

---

README.md

We sometimes open PR that have failing jobs but releases are set from `main` so changing the badges to point to `main` instead of *.

Set readme badges to main branch

---

src/dispatch/status.py
tests/dispatch/test_status.py

One of the responsibilities of the SDK is to categorize function outputs (return values or exceptions raised) into a [`Status`](https://github.com/dispatchrun/dispatch-proto/blob/main/dispatch/sdk/v1/status.proto), so that Dispatch knows a) whether to retry, and b) how to adjust the execution concurrency moving forwards.
The SDK provides two functions for registering handler functions that map base error and output (return value) classes to a `Status`:
```python
register_error_type(cls: Type[Exception], handler: Callable[[Exception], Status])
register_output_type(cls: Type[Any], handler: Callable[[Any], Status])
```
For example usage, see https://github.com/dispatchrun/dispatch-py/blob/main/src/dispatch/integrations/openai.py
Sometimes the user simply wants to map a specific class to a …

Simplify registration of error/output to status mappings

---

examples/auto_retry/test_app.py
examples/getting_started/test_app.py
examples/github_stats/test_app.py
pyproject.toml
src/dispatch/test/client.py
src/dispatch/test/fastapi.py
src/dispatch/test/http.py
src/dispatch/test/httpx.py
src/dispatch/test/service.py
tests/test_client.py
tests/test_fastapi.py
tests/test_http.py

The test components we offer in the `dispatch.test` package were coupled to the `httpx` package, since this is what FastAPI uses internally (e.g. for its test client).
To be able to test other web frameworks (e.g. `flask` from #169), we need to decouple our test components from FastAPI and httpx.
This PR does just that, by using a [protocol](https://mypy.readthedocs.io/en/stable/protocols.html) (i.e. structural typing) for the HTTP client and response.
I've downgraded `httpx` to a dev dependency as a result.

test: decouple test components from httpx

---

README.md
src/dispatch/test/flask.py
tests/test_flask.py

Following on from #169, this PR adds tests for the Flask integration and a quick README section.

Flask integration tests

---

pyproject.toml

The new version includes https://github.com/pyauth/http-message-signatures/pull/11, which means we don't need a workaround on the backend.

Depend on http-message-signatures >= 0.5.0

---

src/dispatch/asyncio.py
src/dispatch/experimental/lambda_handler.py
src/dispatch/fastapi.py
src/dispatch/flask.py
src/dispatch/function.py
src/dispatch/http.py
src/dispatch/scheduler.py
tests/dispatch/test_scheduler.py
tests/test_fastapi.py
tests/test_flask.py
tests/test_http.py

This PR modifies the dispatch-py internals to build on the `asyncio` package in order to better integrate with frameworks like FastAPI, httpx, etc... and any other Python code that uses async/await constructs for I/O operations.
A couple of notable changes:
- The signature of primitive functions is changed to always be `async`, this is the only breaking change
- Due to interacting with the asyncio event loop, there are changes to the order of some operations. Notably, the depth-first traversal does not follow the same order anymore; this shouldn't have any impact on production applications since they wouldn't (shouldn't) rely on the order of async operations
In a few places, we are constructing temporary event loops (using a class similar to `asyncio.Runner`) to convert from blocking to …

interoperability with asyncio (part 1)

---

pyproject.toml
src/dispatch/aiohttp.py
src/dispatch/http.py
tests/test_aiohttp.py

Based on #122, this PR adds a new integration with the `aiohttp` framework, to enable dispatch applications that run on `aiohttp` servers, or use `aiohttp` clients to integrate with the `asyncio` facilities end-to-end.
This change is also a prerequisite to more modifications I want to bring to the SDK, that in my mind are other prerequisites for a sync mode where we can wait on dispatch calls in retrieve their results.
What I would like to get to is an API that matches `asyncio` more closely, for example:
```python
import dispatch
@dispatch.function
async def job():
...
dispatch.run(job())
```
This would cause a call to `job` to be dispatched to the scheduler, then waited on by the `dispatch.run` event loop, with the result returned.
This could also be composed with other `asyncio` …

interoperability with asyncio (part 2): integration with aiohttp

---

src/dispatch/any.py
src/dispatch/proto.py
tests/dispatch/test_any.py
tests/dispatch/test_scheduler.py
tests/test_fastapi.py

This PR updates the SDK to avoid using pickle to serialize inputs and outputs unless necessary.
If an input or output value is a protobuf message, it's now serialized directly.
If an input or output value is primitive (null, boolean, integer, float, string, bytes, timestamp, duration), we serialize it using one of the built-in protobuf wrappers.
If an input or output value is a JSON-like list or dict, we serialize it using the built-in structpb wrappers.

Avoid pickling primitive values and proto messages
